INSERT INTO tribes(t_name, popl) VALUES ("Chero", 596);
INSERT INTO tribes(t_name, popl) VALUES ("Bhutia", 27230);
INSERT INTO tribes(t_name, popl) VALUES ("Irular", 213641);
INSERT INTO tribes(t_name, popl) VALUES ("Kisan", 467288);
INSERT INTO tribes(t_name, popl) VALUES ("Varli", 300000);
INSERT INTO tribes(t_name, popl) VALUES ("Bhils", 17000000);
INSERT INTO tribes(t_name, popl) VALUES ("Munda", 2233661);
INSERT INTO tribes(t_name, popl) VALUES ("Santhal", 7000000);
INSERT INTO tribes(t_name, popl) VALUES ("Bodo", 1450000);
INSERT INTO tribes(t_name, popl) VALUES ("Angami", 141732);
INSERT INTO tribes(t_name, popl) VALUES ("Great Andamanese Tribe", 59);
INSERT INTO tribes(t_name, popl) VALUES ("Kodava", 160000);
INSERT INTO tribes(t_name, popl) VALUES ("Kokna", 1049411);
INSERT INTO problems(prob_type) VALUES ("medical");
INSERT INTO problems(prob_type) VALUES ("financial");
INSERT INTO problems(prob_type) VALUES ("educational");
INSERT INTO specialization(sp_type) VALUES ("agriculture");
INSERT INTO specialization(sp_type) VALUES ("handicraft");
INSERT INTO states(s_name) VALUES ("Maharashtra");
INSERT INTO states(s_name) VALUES ("Andra Pradesh");
INSERT INTO states(s_name) VALUES ("Teleangana");
